### ISSUE TITLE
Error when using `:local/root` in `bb.edn`

### ISSUE THREAD

**Issue by rads** [rads/bbin#5]
I ran into some errors when using `local/deps` and `:local/root` during initial development. That said I need to do some more investigation on what was actually going on. It's possible this may not be an issue anymore.

**Comment by rads** [comment]
I think the root cause here is that the `--deps-root` option in `bb` does not seem to affect the values for `:local/root` in the `:deps` config of `bb.edn`.

When I try to install quickblog, I get the following error because it's using `.` as a local path relative to where I'm calling `quickblog`:
```
$ quickblog
Error building classpath. Manifest type not detected when finding deps for io.github.borkdude/quickblog in coordinate #:local{:root "/Users/rads"}
```
I would expect that the `--deps-root` option would cause the `.` to resolve relative to the `--deps-root`.

That said, I think I can work around this by doing a bit of post-processing during the `bb install`. I can inline the updated `bb.edn` contents using [process substitution](https://www.gnu.org/software/bash/manual/html_node/Process-Substitution.html) instead of using a filesystem path.

**Comment by borkdude** [comment]
Nice edge case: I think you're right that local/root should be relative to the deps-root indeed.

**Comment by borkdude** [comment]
Might be good to make a small repro of this and post it as an issue.

**Comment by rads** [comment]
For `bbin` I did what you suggested and made sure we're using `deps.edn` to fetch deps instead of using the project `bb.edn` with `bb --config`. The `bb --config` approach is only needed if we wanted to run a project's tasks, but I'm not sure if that should even be supported right now:

https://github.com/rads/bbin/commit/6295ae344e455b0e85fbe7da96ddda9acf7fdf89

I can definitely follow up with an issue for Babashka.
